name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Run Unit Tests
      run: |
        dotnet restore
        dotnet build
        dotnet test tests/NosCoreBot.Tests -v m
        
    - run: |
        docker build -f ./src/NosCoreBot/dockerfile -t noscorebot:latest --no-cache .
    - name: Push to ECR
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-west-2
        image: noscorebot:latest
        
    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition.json
        service: noscorebot
        cluster: noscorebot-cluster
        wait-for-service-stability: true    
        force-new-deployment: true
