name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Run Unit Tests
      run: |
        dotnet restore
        dotnet build
        dotnet test tests/NosCoreBot.Tests -v m
        
    - name: Push Containers
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: noscorebot
        registry: '703970026174.dkr.ecr.us-west-2.amazonaws.com'
        tags: latest    
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition.json
        service: noscorebot
        cluster: noscorebot-cluster
        wait-for-service-stability: true    
        force-new-deployment: true
