name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Run Unit Tests
      run: |
        dotnet restore
        dotnet build
        dotnet test tests/NosCoreBot.Tests -v m
        
    - name: Build Docker
      if: github.ref == 'refs/heads/master'
      run: |
        docker build -f ./src/NosCoreBot/dockerfile -t noscorebot:latest --no-cache .
        
    - name: Push to ECR
      if: github.ref == 'refs/heads/master'
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-west-2
        image: noscorebot:latest
     
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy to Amazon ECS
      if: github.ref == 'refs/heads/master'
      uses: brunocascio/ecs-deploy@v2.0.0
      with:
        args: deploy noscorebot-cluster noscorebot -i production/noscorebot:latest --max-definitions 1 --force-new-deployment
