name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Run Unit Tests
      run: |
        dotnet restore
        dotnet build
        dotnet tests test/NosCoreBot.Tests -v m
        
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: |
        chmod -R a+x scripts
        sudo bash ./scripts/docker-publish-travis.sh
